"""The asset catalog: where every visual asset lives and what it looks like.

This module is the single source of truth for the asset **tree** and for the
visual specifications of the game's objects.  Nothing in the gameplay code
contains a file path or a sprite size any more: a caller asks the
:class:`~managers.asset_manager.AssetManager` for a *named* asset (``"idle"``,
``"large"``, ``"fragile"``) and the manager resolves it through the tables
below.

The catalog is deliberately three kinds of thing and no more:

* **Path builders** - how a logical name turns into a file.  The path of an
  asset is a pure function of its part, variant, state and frame number, so
  adding art is a matter of dropping a correctly named file into the tree, not
  of editing a lookup table.
* **Specifications** - the technical requirements from ``docs/ART_BIBLE.md``
  expressed as data: sprite sizes, frame counts, frame times, anchors, and the
  palette used when a look is generated by code instead of loaded from a file.
* **Themes** - how a world is dressed (background art, backdrop colour, star
  colour), so a future world is a configuration entry rather than a code path.

Everything here is plain data: no pygame, no I/O.  Whether a catalogued file
actually exists is the :class:`AssetManager`'s business, which is what lets the
game ship with placeholder art and still run.

Naming conventions (see ``docs/ART_BIBLE.md`` for the full rules)::

    assets/player/base/<variant>/player_<state>_<nn>.png
    assets/player/suits/<variant>/suit_<state>_<nn>.png
    assets/hazards/meteor/meteor_<variant>_<nn>.png
    assets/collectibles/fuel/fuel_<nn>.png
    assets/collectibles/powerups/powerup_<kind>_<nn>.png
    assets/environment/backgrounds/<theme>.png
    assets/environment/platforms/platform_<kind>.png
    assets/ui/<group>/<name>.png

``<variant>`` is omitted for the default variant, so the shipped base frame is
``assets/player/base/player_idle_01.png`` and a future Cyber suit would be
``assets/player/suits/cyber/suit_idle_01.png``.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from enum import Enum

from config.constants import ASSETS_DIR, BG_COLOR, STAR_COLOR

# ---------------------------------------------------------------------------
# The asset tree
# ---------------------------------------------------------------------------
PLAYER_ASSETS_DIR: str = os.path.join(ASSETS_DIR, "player")
HAZARD_ASSETS_DIR: str = os.path.join(ASSETS_DIR, "hazards")
METEOR_ASSETS_DIR: str = os.path.join(HAZARD_ASSETS_DIR, "meteor")
COLLECTIBLE_ASSETS_DIR: str = os.path.join(ASSETS_DIR, "collectibles")
FUEL_ASSETS_DIR: str = os.path.join(COLLECTIBLE_ASSETS_DIR, "fuel")
POWERUP_ASSETS_DIR: str = os.path.join(COLLECTIBLE_ASSETS_DIR, "powerups")
ENVIRONMENT_ASSETS_DIR: str = os.path.join(ASSETS_DIR, "environment")
BACKGROUNDS_DIR: str = os.path.join(ENVIRONMENT_ASSETS_DIR, "backgrounds")
PLATFORMS_DIR: str = os.path.join(ENVIRONMENT_ASSETS_DIR, "platforms")
UI_ASSETS_DIR: str = os.path.join(ASSETS_DIR, "ui")
UI_ICONS_DIR: str = os.path.join(UI_ASSETS_DIR, "icons")
UI_BUTTONS_DIR: str = os.path.join(UI_ASSETS_DIR, "buttons")
UI_PANELS_DIR: str = os.path.join(UI_ASSETS_DIR, "panels")
UI_INDICATORS_DIR: str = os.path.join(UI_ASSETS_DIR, "indicators")

#: Directories the game expects to exist, so a missing one is a clear startup
#: warning rather than a mystery at draw time.
ASSET_DIRS: tuple[str, ...] = (
    PLAYER_ASSETS_DIR,
    METEOR_ASSETS_DIR,
    FUEL_ASSETS_DIR,
    POWERUP_ASSETS_DIR,
    BACKGROUNDS_DIR,
    PLATFORMS_DIR,
    UI_ICONS_DIR,
)

#: The name given to the asset variant that ships with the game.  Files of the
#: default variant live directly in their part folder, without a variant level.
DEFAULT_VARIANT: str = "default"


class Anchor(Enum):
    """Where a sprite is pinned to its collision rectangle.

    Keeping the anchor explicit is what stops art from moving the collision
    body: a sprite is *drawn* relative to the rectangle, never the other way
    round.  A taller or wider sprite grows away from the anchor.
    """

    TOPLEFT = "topleft"
    CENTER = "center"
    BOTTOM_CENTER = "bottom_center"


# ---------------------------------------------------------------------------
# Player: parts, states and clips
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class PlayerPartSpec:
    """One layer of the player character."""

    #: Logical name, as used by ``PlayerSkin``.
    name: str
    #: Folder under ``assets/player`` its art lives in.
    folder: str
    #: Filename prefix, e.g. ``player_idle_01.png`` for the base layer.
    prefix: str
    #: Composition order; the base layer is drawn first, effects last.
    order: int


#: The layers a player is composed from, drawn in ``order``.  Only ``base``
#: ships with art today; the rest are drawn only when a skin supplies them, so
#: a future suit is a folder of PNGs and a one-line skin definition.
PLAYER_PARTS: tuple[PlayerPartSpec, ...] = (
    PlayerPartSpec("base", "base", "player", 0),
    PlayerPartSpec("suit", "suits", "suit", 1),
    PlayerPartSpec("helmet", "helmets", "helmet", 2),
    PlayerPartSpec("backpack", "backpacks", "backpack", 3),
    PlayerPartSpec("accessory", "accessories", "accessory", 4),
    PlayerPartSpec("effects", "effects", "effect", 5),
)

PLAYER_PART_BY_NAME: dict[str, PlayerPartSpec] = {
    part.name: part for part in PLAYER_PARTS
}

#: The default variant of every part: the art that ships with the game.
DEFAULT_SKIN_PARTS: dict[str, str] = {
    part.name: DEFAULT_VARIANT for part in PLAYER_PARTS
}


@dataclass(frozen=True)
class ClipSpec:
    """A player animation: how many frames it has and how fast it plays.

    ``frames`` is how many numbered files the state *may* have.  Missing frames
    are not an error: a state with no art of its own resolves up the
    ``fallback`` chain, so the architecture supports Idle / Jump / Fall /
    Landing / Hurt / Death while only Idle has to exist.
    """

    frames: int = 1
    #: Seconds each frame is shown for.  Timing is data, never a frame counter,
    #: so animation speed is identical at 30, 60, 120 and 144 FPS.
    frame_time: float = 0.2
    loop: bool = True
    #: State to borrow art from when this state has none of its own.
    fallback: str | None = "idle"


#: One entry per ``PlayerVisualState`` (keyed by its value).
PLAYER_CLIPS: dict[str, ClipSpec] = {
    "idle": ClipSpec(frames=1, frame_time=0.6, loop=True, fallback="idle"),
    "jump": ClipSpec(frames=1, frame_time=0.12, loop=False, fallback="idle"),
    "fall": ClipSpec(frames=1, frame_time=0.12, loop=False, fallback="idle"),
    "landing": ClipSpec(frames=1, frame_time=0.10, loop=False, fallback="idle"),
    "hurt": ClipSpec(frames=1, frame_time=0.10, loop=False, fallback="idle"),
    "death": ClipSpec(frames=1, frame_time=0.14, loop=False, fallback="idle"),
}

#: How long the Landing pose is held after touchdown, in seconds.  Landing is a
#: visual state only; it never delays a jump (the jump buffer still fires).
LANDING_HOLD: float = 0.10

#: Directions a sprite may face.  Mirroring is pre-computed and cached, so a
#: direction change never transforms an image inside the frame loop.
PLAYER_FACINGS: tuple[int, ...] = (1, -1)


def player_frame_path(
    state: str, *, part: str = "base", variant: str = DEFAULT_VARIANT, index: int = 1
) -> str:
    """Return the path of one player frame.

    Args:
        state: Clip name, e.g. ``"idle"``.
        part: Layer name from :data:`PLAYER_PARTS`.
        variant: Skin variant of that layer; ``"default"`` keeps the file in
            the part folder itself.
        index: 1-based frame number.
    """
    spec = PLAYER_PART_BY_NAME[part]
    folder = os.path.join(PLAYER_ASSETS_DIR, spec.folder)
    if variant != DEFAULT_VARIANT:
        folder = os.path.join(folder, variant)
    return os.path.join(folder, f"{spec.prefix}_{state}_{index:02d}.png")


# ---------------------------------------------------------------------------
# Meteorites: visual variants
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class MeteorVariantSpec:
    """The look of one meteorite variant.

    Only the *sprite* size lives here.  The collision rectangle stays
    :data:`~config.constants.METEORITE_SIZE` for every variant, so choosing a
    look can never change how hard a hazard is to avoid.
    """

    name: str
    sprite_size: tuple[int, int]
    frames: int = 1
    frame_time: float = 0.12
    #: Whether the sprite is pre-rotated through a cycle of cached angles.
    spin: bool = False
    #: How many distinct rotations are pre-computed when ``spin`` is set.
    rotation_steps: int = 24


#: Visual variants the pipeline knows.  Gameplay still spawns
#: :data:`METEOR_DEFAULT_VARIANT` only; the rest exist so art can be dropped in
#: without touching the meteorite class.
METEOR_VARIANTS: dict[str, MeteorVariantSpec] = {
    "small": MeteorVariantSpec("small", (28, 28)),
    "medium": MeteorVariantSpec("medium", (40, 40)),
    "large": MeteorVariantSpec("large", (56, 56)),
    "burning": MeteorVariantSpec("burning", (40, 40)),
}

DEFAULT_METEOR_VARIANT: str = "medium"
#: Variant whose art is used when a variant has no art of its own.  Sizes
#: still come from the requested variant, so a missing file changes the
#: picture, never the footprint.
METEOR_ART_FALLBACK: str = "medium"


def meteor_frame_path(variant: str, index: int = 1) -> str:
    """Return the path of one meteorite frame."""
    return os.path.join(METEOR_ASSETS_DIR, f"meteor_{variant}_{index:02d}.png")


# ---------------------------------------------------------------------------
# Collectibles
# ---------------------------------------------------------------------------
#: Fuel canister animation: one frame today, more by adding ``fuel_02.png``.
FUEL_FRAMES: int = 1
FUEL_FRAME_TIME: float = 0.25
#: Fuel keeps its whole silhouette: a hazard never uses this art, and a
#: collectible never uses the hazard palette.
FUEL_ANCHOR: Anchor = Anchor.CENTER


def fuel_frame_path(index: int = 1) -> str:
    """Return the path of one fuel canister frame."""
    return os.path.join(FUEL_ASSETS_DIR, f"fuel_{index:02d}.png")


#: Power-ups are generated from code today (they are simple shapes), but they
#: follow the same convention so an icon can replace them later.
POWERUP_FRAMES: int = 1
POWERUP_FRAME_TIME: float = 0.2


def powerup_frame_path(kind: str, index: int = 1) -> str:
    """Return the path of one power-up frame."""
    return os.path.join(POWERUP_ASSETS_DIR, f"powerup_{kind}_{index:02d}.png")


# ---------------------------------------------------------------------------
# Environment: platform looks and world themes
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class PlatformLook:
    """How one platform kind is rendered.

    A ``file`` may replace the generated look later; until then the palette
    below is drawn in code, once per (kind, size), and cached.
    """

    name: str
    body: tuple[int, int, int]
    highlight: tuple[int, int, int]
    shadow: tuple[int, int, int]
    radius: int = 6


#: Body colours are the ones Phase 3 used, so a platform still reads as the
#: same thing it always did; the highlight and shadow are what make it a
#: rounded, lit object instead of a flat bar.
PLATFORM_LOOKS: dict[str, PlatformLook] = {
    "normal": PlatformLook(
        "normal",
        body=(200, 200, 200),
        highlight=(245, 245, 255),
        shadow=(120, 120, 140),
    ),
    "moving": PlatformLook(
        "moving",
        body=(100, 100, 255),
        highlight=(170, 170, 255),
        shadow=(50, 50, 160),
    ),
    "fragile": PlatformLook(
        "fragile",
        body=(255, 80, 80),
        highlight=(255, 170, 150),
        shadow=(150, 30, 40),
    ),
}

#: Platform kinds the rendering pipeline accepts.  Only ``normal``, ``moving``
#: and ``fragile`` are generated today; the table is what a future
#: "special"/"hazard" platform extends.
DEFAULT_PLATFORM_LOOK: str = "normal"


def platform_art_path(kind: str) -> str:
    """Return the path of optional platform art for *kind*."""
    return os.path.join(PLATFORMS_DIR, f"platform_{kind}.png")


@dataclass(frozen=True)
class ThemeSpec:
    """The dress of one world: backdrop art, backdrop colour, star colour.

    Gameplay never reads a background file path: it asks for a theme, and a
    theme without art falls back to a flat backdrop plus the starfield, which
    is exactly what the game shows today.
    """

    name: str
    #: Backdrop image, or ``None`` to paint :attr:`bg_color` instead.
    background: str | None = None
    bg_color: tuple[int, int, int] = BG_COLOR
    star_color: tuple[int, int, int] = STAR_COLOR
    #: Multiplier on the starfield's drift, so a "deep space" world can feel
    #: slower than a "clouds" one without touching the physics.
    star_drift_scale: float = 1.0


#: The worlds the pipeline can dress.  Only ``space`` is implemented; the rest
#: are the names the Art Bible reserves for later phases.
ENVIRONMENT_THEMES: dict[str, ThemeSpec] = {
    "space": ThemeSpec("space"),
    "earth": ThemeSpec("earth", background=None, bg_color=(20, 40, 70)),
    "moon": ThemeSpec("moon", background=None, bg_color=(18, 18, 26)),
    "mars": ThemeSpec("mars", background=None, bg_color=(60, 26, 20)),
}

DEFAULT_THEME: str = "space"


def theme_spec(name: str) -> ThemeSpec:
    """Return the theme named *name*, falling back to the default one."""
    return ENVIRONMENT_THEMES.get(name, ENVIRONMENT_THEMES[DEFAULT_THEME])


def background_path(theme: str) -> str:
    """Return the path of the backdrop art for *theme*."""
    return os.path.join(BACKGROUNDS_DIR, f"{theme}.png")


# ---------------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class UiAssetSpec:
    """One future UI asset: its folder, size and whether it must be artwork.

    Phase 5 owns the UI itself.  Declaring the names now means the menu work
    later is asset placement rather than architecture.
    """

    name: str
    folder: str
    size: tuple[int, int]
    #: ``True`` when an icon has to be artwork (there is no sensible code
    #: fallback); ``False`` when drawing it in code is fine.
    artwork_required: bool = False


UI_ICONS: dict[str, UiAssetSpec] = {
    "fuel": UiAssetSpec("fuel", UI_ICONS_DIR, (24, 24), artwork_required=True),
    "score": UiAssetSpec("score", UI_ICONS_DIR, (24, 24), artwork_required=True),
    "stage": UiAssetSpec("stage", UI_ICONS_DIR, (24, 24), artwork_required=True),
    "pause": UiAssetSpec("pause", UI_ICONS_DIR, (32, 32), artwork_required=True),
}


def ui_asset_path(spec: UiAssetSpec) -> str:
    """Return the path of a UI asset."""
    return os.path.join(spec.folder, f"{spec.name}.png")


# ---------------------------------------------------------------------------
# The player's visual footprint
# ---------------------------------------------------------------------------
#: Offset from the bottom of the collision rectangle to the sprite's feet.
#: Zero means the art's lowest pixel *is* the standing surface; a positive
#: value would lift the art to leave room for a shadow or a jet flame.
PLAYER_FOOT_OFFSET: int = 0
#: Anchor of every player frame.  A new animation must keep the feet on this
#: line, which is what stops a suit from appearing to hover.
PLAYER_ANCHOR: Anchor = Anchor.BOTTOM_CENTER


@dataclass(frozen=True)
class ArtNote:
    """A finding from the asset audit, quoted by the Art Bible."""

    asset: str
    verdict: str


#: The result of auditing the art that ships with the game.
ART_AUDIT: tuple[ArtNote, ...] = (
    ArtNote(
        "assets/player/base/player_idle_01.png",
        "3072x3072 RGBA placeholder, 62x larger than its 50x50 gameplay size; "
        "redraw at 100x100 for a crisp 2x target.",
    ),
    ArtNote(
        "assets/hazards/meteor/meteor_medium_01.png",
        "360x360 RGBA placeholder; needs a medium variant set with matching "
        "silhouettes for small/large/burning.",
    ),
    ArtNote(
        "assets/collectibles/fuel/fuel_01.png",
        "512x512 RGBA placeholder, previously named 5998974.PNG; needs the "
        "cyan/orange collectible palette so it cannot read as a hazard.",
    ),
    ArtNote(
        "assets/fonts/The Visitor.otf",
        "Display font, kept: it already matches the stylised sci-fi direction.",
    ),
)
